site_name: Michigan Imputation Server
repo_name: genepi/imputationserver
repo_url: https://github.com/genepi/imputationserver
edit_uri: edit/master/docs

theme:
  name: material
  features:
    - content.tooltips
    #- navigation.expand
    - navigation.tabs
    #- navigation.tabs.sticky
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    #- toc.integrate
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  font:
    text: Segoe UI #Avenir
    code: Roboto Mono

  palette:
    primary: custom
    accent: blue
  favicon: images/favicon.svg

extra_css:
  - stylesheets/extra.css

nav:
- Home: index.md
- Genotype Imputation:
  - Getting Started: getting-started.md
  - Data Preparation: prepare-your-data.md
  - Reference Panels: reference-panels.md
  - Pipeline Overview: pipeline.md
  - Security: data-sensitivity.md
  - FAQ: faq.md
- Polygenic Score Calculation:
    - Getting Started: pgs/getting-started.md
    - Step-by-Step Tutorial: pgs/tutorial.md
    - Interactive Report: pgs/report.md
    - Output Files: pgs/output-files.md
    - Reference Panels: pgs/reference-panels.md
    - Available Scores: pgs/scores.md
    - Pipeline Overview: pgs/pipeline.md
    - FAQ: pgs/faq.md
- Developer Documentation:
  - API: api.md
  - Docker: docker.md
  - Creating Reference Panels: create-reference-panels.md
- Workshops:
  - ASHG2023:
    - Overview: workshops/ASHG2023.md
    - "Session 1: Imputation and the Server": workshops/ASHG2023/Session1.md
    - "Session 2: Run a job, Data Preparation and Data Download": workshops/ASHG2023/Session2.md
    - "Session 3: Performing GWAS using imputed data": workshops/ASHG2023/Session3.md
    - "Session 4: nf-gwas, Imputation Bot and PGS Server": workshops/ASHG2023/Session4.md
    - "Session 5: HLA Imputation": workshops/ASHG2023/Session5.md
    - "Session 6: TOPMed Imputation Server": workshops/ASHG2023/Session6.md
- Contact: contact.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      title: On this page
      permalink: true